import type { GameDefinition } from "../../RestaurantCommon/src/game/types";
export const pizza: GameDefinition = {
  id: "pizza",
  title: "Pizza Piazza",
  subtitle: {
    cs: "Kousek Itálie. Celý tvůj.",
    en: "A little Italy. All yours.",
  },
  accent: "#db5145",
  dark: "#315c43",
  background: "#bdcfa7",
  price: 12,
  speed: 5,
  stations: [
    {
      id: "source",
      kind: "source",
      x: -5.6,
      z: -6.5,
      label: { cs: "Těsto", en: "Dough" },
      input: null,
      output: "raw",
      seconds: 2.2,
      batch: 1,
      unlock: 0,
    },
    {
      id: "prep",
      kind: "convert",
      x: 0,
      z: -6.5,
      label: { cs: "Příprava", en: "Toppings" },
      input: "raw",
      output: "prep",
      seconds: 1,
      batch: 1,
      unlock: 0,
    },
    {
      id: "oven",
      kind: "oven",
      x: 5.6,
      z: -6.5,
      label: { cs: "Pec", en: "Oven" },
      input: "prep",
      output: "meal",
      seconds: 2.8,
      batch: 3,
      unlock: 0,
    },
    {
      id: "counter",
      kind: "counter",
      x: -5,
      z: 2,
      label: { cs: "Výdej", en: "Counter" },
      input: "meal",
      output: "meal",
      seconds: 0,
      batch: 1,
      unlock: 0,
    },
    {
      id: "drive",
      kind: "counter",
      x: -7,
      z: -1.5,
      label: { cs: "Rozvoz", en: "Delivery" },
      input: "meal",
      output: "meal",
      seconds: 0,
      batch: 1,
      unlock: 9,
    },
    {
      id: "annex",
      kind: "oven",
      x: 0,
      z: -13,
      label: { cs: "Nová pec", en: "Annex oven" },
      input: "prep",
      output: "meal",
      seconds: 1.5,
      batch: 3,
      unlock: 15,
    },
    {
      id: "dispatch",
      kind: "counter",
      x: 13,
      z: -5,
      label: { cs: "Expresní výdej", en: "Express counter" },
      input: "meal",
      output: "meal",
      seconds: 0,
      batch: 1,
      unlock: 16,
    },
  ],
  unlocks: [
    {
      name: { cs: "První stoleček", en: "First table" },
      description: {
        cs: "Přivítej první hosty u stolu.",
        en: "Welcome your first seated guests.",
      },
      cost: 24,
      icon: "chair",
    },
    {
      name: { cs: "Ještě dvě místa", en: "Room for two" },
      description: {
        cs: "Malá pizzerie začíná růst.",
        en: "Your little pizzeria is growing.",
      },
      cost: 60,
      icon: "chair",
    },
    {
      name: { cs: "Nový hnětač", en: "Dough mixer" },
      description: {
        cs: "Dvojnásobná výroba čerstvého těsta.",
        en: "Twice the fresh dough.",
      },
      cost: 150,
      icon: "fire",
    },
    {
      name: { cs: "Rodinný tým", en: "Family team" },
      description: {
        cs: "Připrav zázemí pro zaměstnance.",
        en: "Make room for your new team.",
      },
      cost: 250,
      icon: "team",
    },
    {
      name: { cs: "Pokladní Sofia", en: "Sofia, the cashier" },
      description: {
        cs: "Zákazníci zaplatí i bez tvé pomoci.",
        en: "Your guests can pay without your help.",
      },
      cost: 300,
      icon: "team",
    },
    {
      name: { cs: "Letní terasa", en: "Summer terrace" },
      description: {
        cs: "Dva nové stoly a salámová pizza.",
        en: "Two new tables and a pepperoni recipe.",
      },
      cost: 500,
      icon: "chair",
    },
    {
      name: { cs: "Pizzař Luca", en: "Luca, the pizzaiolo" },
      description: {
        cs: "Přenáší těsto a zásobuje pec.",
        en: "Prepares dough and keeps the oven busy.",
      },
      cost: 700,
      icon: "team",
    },
    {
      name: { cs: "Uklízečka Eva", en: "Eva, the cleaner" },
      description: {
        cs: "Čisté stoly bez starostí.",
        en: "Fresh tables, without the chores.",
      },
      cost: 900,
      icon: "spark",
    },
    {
      name: { cs: "Rozvoz skútry", en: "Scooter delivery" },
      description: {
        cs: "Čerstvá pizza míří do celého sousedství.",
        en: "Deliver pizza around the neighborhood.",
      },
      cost: 1500,
      icon: "car",
    },
    {
      name: { cs: "Dvojitá pec", en: "Double oven" },
      description: {
        cs: "Rychlejší pečení a zeleninová specialita.",
        en: "Faster baking and a garden special.",
      },
      cost: 2200,
      icon: "fire",
    },
    {
      name: { cs: "Kurýr Marco", en: "Marco, the runner" },
      description: {
        cs: "Balí pizzy a zásobuje výdej i rozvoz.",
        en: "Packs pizzas for your counter and riders.",
      },
      cost: 3000,
      icon: "team",
    },
    {
      name: { cs: "La dolce vita", en: "La dolce vita" },
      description: {
        cs: "Tvá restaurace je připravena na další kapitolu.",
        en: "Your restaurant is ready for its next chapter.",
      },
      cost: 8000,
      icon: "star",
    },
    {
      name: { cs: "Východní jídelna", en: "East dining wing" },
      description: {
        cs: "Přístavba se čtyřmi stoly a o 5 míst větší tácy.",
        en: "Open a dining wing with four tables and carry 5 more items.",
      },
      cost: 3500,
      icon: "bag",
    },
    {
      name: { cs: "Zahradní terasa", en: "Garden terrace" },
      description: {
        cs: "Nová terasa se čtyřmi stoly a o 35 % rychlejší tým.",
        en: "Open a terrace with four tables and a 35% faster team.",
      },
      cost: 4500,
      icon: "team",
    },
    {
      name: { cs: "Severní kuchyně", en: "North kitchen" },
      description: {
        cs: "Rozšiř kuchyni o výrobní stanici a prémiový recept.",
        en: "Add a working kitchen annex and unlock a signature recipe.",
      },
      cost: 5500,
      icon: "star",
    },
    {
      name: { cs: "Expresní křídlo", en: "Express wing" },
      description: {
        cs: "Nové křídlo s výdejem a o 50 % rychlejší výroba.",
        en: "Open an express counter wing and produce 50% faster.",
      },
      cost: 6500,
      icon: "fire",
    },
    {
      name: { cs: "Prémiový salonek", en: "Premium lounge" },
      description: {
        cs: "Dva další stoly v salonku a o 20 % vyšší tržby.",
        en: "Add two lounge tables and earn 20% more on every order.",
      },
      cost: 8000,
      icon: "spark",
    },
    {
      name: { cs: "Vstupní zahrada", en: "Entrance garden" },
      description: {
        cs: "Otevři slavnostní zahradu a získej o 50 % více offline.",
        en: "Open the landmark garden and earn 50% more offline income.",
      },
      cost: 10000,
      icon: "star",
    },
  ],
  recipes: [
    { cs: "Margherita", en: "Margherita" },
    { cs: "Salámová", en: "Pepperoni" },
    { cs: "Zeleninová", en: "Garden special" },
    { cs: "Lanýžová specialita", en: "Truffle special" },
  ],
  recipeLevels: [0, 6, 10, 15],
};
